In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3])

b = np.array([4,5,6])

print(a+b)

[5 7 9]


In [ ]:
print(a-b)

[-3 -3 -3]


In [ ]:
print(a*b)

[ 4 10 18]


In [ ]:
print(a/b)

[0.25 0.4  0.5 ]


In [ ]:
print(a**3) # square

[ 1  8 27]


In [ ]:
print(np.sqrt(a)) # to find the sq root

[1.         1.41421356 1.73205081]


In [ ]:
print(np.power(a,2)) # for n exponent

[1 4 9]


In [ ]:
arr = np.array([10,20,30,40,50]) # defining 1d array

In [ ]:
print(np.mean(arr)) # to find the average

30.0


In [ ]:
print(np.median(arr)) # to find median value

30.0


In [ ]:
print(np.max(arr)) # highest value

50


In [ ]:
print(np.min(arr)) # lowest value

10


In [ ]:
print(np.sum(arr)) # total value

150


In [ ]:
print(np.std(arr)) # standard deviation

14.142135623730951


In [ ]:
print(np.var(arr)) # variance

200.0


In [ ]:
arr = np.array([1,2,3,4,5,6])

print(arr.reshape(2,3))

[[1 2 3]
 [4 5 6]]


In [ ]:
arr = np.array([[1,2],[3,4]])

print(arr.flatten())

[1 2 3 4]


In [ ]:
arr = np.array([[1,2,3],
                [4,5,6]])

print(arr.T)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.arange(1,11) # array in particular range

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.random.rand(5) # give random numbers below 1

array([0.24318388, 0.21890422, 0.43821218, 0.48516823, 0.78838058])

In [ ]:
np.random.randint(1,100,10) # give random integers

array([16, 14, 15, 62, 24, 76, 19, 37, 76, 12])

In [ ]:
arr = np.array([5,2,9,1])

print(np.sort(arr))

[1 2 5 9]


In [ ]:
arr = np.array([1,2,2,3,3,4])

print(np.unique(arr))

[1 2 3 4]


In [ ]:
a = np.array([1,2,3])

b = np.array([4,5,6])

print(np.concatenate((a,b)))

[1 2 3 4 5 6]


In [ ]:
arr = np.array([1,2,3,4,5,6])

print(np.split(arr,3))

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
arr = np.array([10,20,30,40,50])

print(arr[arr>25])

[30 40 50]


In [ ]:
w