In [ ]:
import pandas as pd

data = {
    "Student_ID": [101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120],

    "Name": ["Aman","Neha","Rahul","Priya","Karan","Simran","Mohit","Anjali","Vikas","Pooja","Rohit","Sneha","Arjun","Riya","Deepak","Muskan","Yash","Komal","Abhishek","Nisha"],

    "Gender": ["Male","Female","Male","Female","Male","Female","Male","Female","Male","Female","Male","Female","Male","Female","Male","Female","Male","Female","Male","Female"],

    "Age": [20,21,19,22,20,21,20,19,22,20,21,20,23,19,22,20,21,22,20,19],

    "Department": ["CSE","IT","ECE","CSE","IT","CSE","ECE","IT","CSE","ECE","IT","CSE","ECE","IT","CSE","ECE","IT","CSE","ECE","IT"],

    "Semester": [4,4,2,6,4,6,2,4,8,6,2,8,6,4,8,2,6,4,8,2],

    "Marks": [85,92,78,95,67,88,72,91,81,76,69,94,73,89,97,66,82,90,79,84],

    "Attendance": [92,95,85,97,78,90,82,98,88,84,80,96,83,91,99,76,89,94,87,92],"CGPA": [8.5,9.2,7.8,9.5,6.9,8.8,7.2,9.1,8.1,7.6,7.0,9.4,7.4,8.9,9.8,6.8,8.2,9.0,7.9,8.4],"City": ["Delhi","Lucknow","Noida","Jaipur","Delhi","Noida","Lucknow","Delhi","Jaipur","Delhi","Noida","Lucknow","Delhi","Jaipur","Delhi","Noida","Lucknow","Delhi","Jaipur","Delhi"]
}

df = pd.DataFrame(data)
print(df)


    Student_ID      Name  Gender  Age Department  Semester  Marks  Attendance  \
0          101      Aman    Male   20        CSE         4     85          92   
1          102      Neha  Female   21         IT         4     92          95   
2          103     Rahul    Male   19        ECE         2     78          85   
3          104     Priya  Female   22        CSE         6     95          97   
4          105     Karan    Male   20         IT         4     67          78   
5          106    Simran  Female   21        CSE         6     88          90   
6          107     Mohit    Male   20        ECE         2     72          82   
7          108    Anjali  Female   19         IT         4     91          98   
8          109     Vikas    Male   22        CSE         8     81          88   
9          110     Pooja  Female   20        ECE         6     76          84   
10         111     Rohit    Male   21         IT         2     69          80   
11         112     Sneha  Fe

In [ ]:
import numpy as np


In [ ]:
array=np.array([[10,20,30],
 [20,30,40]])
print (array)

[[10 20 30]
 [20 30 40]]


In [ ]:
print("hello world")

hello world


In [ ]:
array=np.array([[[10,20],[30,40]],[[80,90],[60,70]]])
print (array)

[[[10 20]
  [30 40]]

 [[80 90]
  [60 70]]]


In [ ]:
print(array.ndim)

3


In [ ]:
print(array.shape)
print(array.size)

(2, 2, 2)
8


In [ ]:
import numpy as np
a=np.array([12,21])
b=np.array([34,43])
print(a,b)

[12 21] [34 43]


In [ ]:
print(a/b)
print(a%b)
print(a*b)
print(a-b)
print(a+b)
print(a**(1/2))
print(np.power(a,2))

[0.35294118 0.48837209]
[12 21]
[408 903]
[-22 -22]
[46 64]
[3.46410162 4.58257569]
[144 441]


In [ ]:
arr=np.array([10,20,30,40,50])
print(np.mean(arr))

30.0


In [ ]:
print(np.max(arr)) #highest value

50


In [ ]:
print(np.min(arr))
print(np.sum(arr))

10
150
